declare namespace GrandTheftMultiplayer.Client.Javascript {

	class BooleanEvent {
		constructor(object: any, method: any);
		Invoke(value: boolean): void;
		BeginInvoke(value: boolean, callback: System.AsyncCallback, object: any): System.IAsyncResult;
		EndInvoke(result: System.IAsyncResult): void;
	}

	class GlobalCamera {
		readonly Active: boolean;
		readonly AttachOffset: GrandTheftMultiplayer.Shared.Math.Vector3;
		readonly BoneAttached: number;
		readonly BonePointing: number;
		readonly CamObj: GTA.Camera;
		readonly EntityAttached: number;
		readonly EntityPointing: number;
		readonly Fov: number;
		readonly PointOffset: GrandTheftMultiplayer.Shared.Math.Vector3;
		readonly Position: GrandTheftMultiplayer.Shared.Math.Vector3;
		readonly Rotation: GrandTheftMultiplayer.Shared.Math.Vector3;
		readonly Shake: string;
		readonly ShakeAmp: number;
		readonly VectorPointing: GrandTheftMultiplayer.Shared.Math.Vector3;
		constructor();
	}

	class IntegerEvent {
		constructor(object: any, method: any);
		Invoke(value: number): void;
		BeginInvoke(value: number, callback: System.AsyncCallback, object: any): System.IAsyncResult;
		EndInvoke(result: System.IAsyncResult): void;
	}

	class JavascriptChat {
		CurrentInput: string;
		IsFocused: boolean;
		SanitationLevel: number;
		onAddMessageRequest: IEvent<(msg: string, hasColor: boolean, r: number, g: number, b: number) => void>;
		onCharInput: IEvent<(value: number) => void>;
		onChatHideRequest: IEvent<(value: boolean) => void>;
		onClearRequest: IEvent<() => void>;
		OnComplete: IEvent<(sender: any, e: System.EventArgs) => void>;
		onFocusChange: IEvent<(value: boolean) => void>;
		onInit: IEvent<() => void>;
		onKeyDown: IEvent<(sender: any, e: System.Windows.Forms.KeyEventArgs) => void>;
		onTick: IEvent<() => void>;
		constructor();
		AddMessage(sender: string, message: string): void;
		Clear(): void;
		Init(): void;
		OnKeyDown(e: System.Windows.Forms.KeyEventArgs): void;
		sendMessage(msg: string): void;
		Tick(): void;
	}

	class MenuPoolWrapper {
		constructor();
		Add(menu: NativeUI.UIMenu): void;
		Show(menu: NativeUI.UIMenu): void;
		Hide(menu: NativeUI.UIMenu): void;
		HasAnyMenuOpen(): boolean;
		ProcessMenus(run?: boolean): void;
	}

	class MessageEvent {
		constructor(object: any, method: any);
		Invoke(msg: string, hasColor: boolean, r: number, g: number, b: number): void;
		BeginInvoke(msg: string, hasColor: boolean, r: number, g: number, b: number, callback: System.AsyncCallback, object: any): System.IAsyncResult;
		EndInvoke(result: System.IAsyncResult): void;
	}

	class ScriptContext {
		onResourceStart: IEvent<() => void>;
		onResourceStop: IEvent<() => void>;
		onUpdate: IEvent<() => void>;
		onHudVisibilityChange: IEvent<(visible: boolean) => void>;
		onKeyDown: IEvent<(sender: any, e: System.Windows.Forms.KeyEventArgs) => void>;
		onKeyUp: IEvent<(sender: any, e: System.Windows.Forms.KeyEventArgs) => void>;
		onServerEventTrigger: IEvent<(eventName: string, _arguments: System.Array<any>) => void>;
		onChatMessage: IEvent<(msg: string) => void>;
		onChatCommand: IEvent<(msg: string) => void>;
		onEntityStreamIn: IEvent<(item: GrandTheftMultiplayer.Client.Models.LocalHandle, entityType: number) => void>;
		onEntityStreamOut: IEvent<(item: GrandTheftMultiplayer.Client.Models.LocalHandle, entityType: number) => void>;
		onEntityDataChange: IEvent<(entity: GrandTheftMultiplayer.Client.Models.LocalHandle, key: string, oldValue: any) => void>;
		onCustomDataReceived: IEvent<(data: string, dataID: number) => void>;
		onPlayerDeath: IEvent<(killer: GrandTheftMultiplayer.Client.Models.LocalHandle, weapon: number) => void>;
		onPlayerRespawn: IEvent<() => void>;
		onPlayerPickup: IEvent<(entity: GrandTheftMultiplayer.Client.Models.LocalHandle) => void>;
		onPlayerEnterVehicle: IEvent<(entity: GrandTheftMultiplayer.Client.Models.LocalHandle, seat: number) => void>;
		onPlayerExitVehicle: IEvent<(entity: GrandTheftMultiplayer.Client.Models.LocalHandle, seat: number) => void>;
		onPlayerChangeVehicleSeat: IEvent<(entity: GrandTheftMultiplayer.Client.Models.LocalHandle, oldSeat: number, newSeat: number) => void>;
		onVehicleHealthChange: IEvent<(oldValue: number) => void>;
		onVehicleDoorBreak: IEvent<(oldValue: number) => void>;
		onVehicleWindowSmash: IEvent<(oldValue: number) => void>;
		onPlayerHealthChange: IEvent<(oldValue: number) => void>;
		onPlayerArmorChange: IEvent<(oldValue: number) => void>;
		onPlayerWeaponSwitch: IEvent<(oldValue: number) => void>;
		onPlayerModelChange: IEvent<(oldValue: number) => void>;
		onVehicleSirenToggle: IEvent<() => void>;
		onPlayerDetonateStickies: IEvent<() => void>;
		onVehicleTyreBurst: IEvent<(oldValue: number) => void>;
		onLocalPlayerDamaged: IEvent<(attacker: GrandTheftMultiplayer.Client.Models.LocalHandle, weaponUsed: number, boneHit: number) => void>;
		onLocalPlayerMeleeHit: IEvent<(attacker: GrandTheftMultiplayer.Client.Models.LocalHandle, weaponUsed: number) => void>;
		onLocalPlayerShoot: IEvent<(weaponUsed: number, aimCoords: GrandTheftMultiplayer.Shared.Math.Vector3) => void>;
		onEntityMovingPositionFinished: IEvent<(obj: GrandTheftMultiplayer.Client.Models.LocalHandle) => void>;
		onEntityMovingRotationFinished: IEvent<(obj: GrandTheftMultiplayer.Client.Models.LocalHandle) => void>;
		onDynamicMenuListItemChanged: IEvent<(sender: NativeUI.UIMenuDynamicListItem, direction: NativeUI.UIMenuDynamicListItem.ChangeDirection) => void>;
		constructor(engine: any);
		getCharFromKey(key: number, shift: boolean, ctrl: boolean, alt: boolean): string;
		createObject(model: number, pos: GrandTheftMultiplayer.Shared.Math.Vector3, rotation: GrandTheftMultiplayer.Shared.Math.Vector3): GrandTheftMultiplayer.Client.Models.LocalHandle;
		createTextTimerBar(label: string, text: string): NativeUI.TextTimerBar;
		createBarTimerBar(label: string): NativeUI.BarTimerBar;
		setTextTimerBarText(timerBar: NativeUI.TextTimerBar, text: string): void;
		setBarTimerBarColor(timerBar: NativeUI.BarTimerBar, r: number, g: number, b: number, a: number): void;
		setBarTimerBarBackgroundColor(timerBar: NativeUI.BarTimerBar, r: number, g: number, b: number, a: number): void;
		setBarTimerPercentage(timerBar: NativeUI.BarTimerBar, percentage: number): void;
		deleteTimerBar(timerBarBase: NativeUI.TimerBarBase): void;
		getAllLoadedAsiNames(): System.Array<any>;
		isOpenIVActive(): boolean;
		isAsiLoaded(asiName: string): boolean;
		getLoadedAsiHash(asiName: string): string;
		getAllActiveModDlcPacksNames(): System.Array<any>;
		isModDlcPackActive(modDlcPack: string): boolean;
		getModDlcPackHash(modDlcPack: string): string;
		getAllCustomScriptsNames(): System.Array<any>;
		getCustomScriptHash(customScriptName: string): string;
		getAnimCurrentTime(handle: GrandTheftMultiplayer.Client.Models.LocalHandle, animDict: string, animName: string): number;
		getAnimTotalTime(handle: GrandTheftMultiplayer.Client.Models.LocalHandle, animDict: string, animName: string): number;
		getAnimTotalTime(animDict: string, animName: string): number;
		getGameFramerate(): number;
		getGameText(labelName: string): string;
		getGameTime(): number;
		getGlobalTime(): number;
		getHashKey(input: string): number;
		verifyIntegrityOfCache(): void;
		getCultureISOLanguageName(): string;
		startMusic(path: string, looped?: boolean): void;
		stopMusic(): void;
		setMusicVolume(volume: number): void;
		getMusicVolume(): number;
		setMusicTime(time: number): void;
		isMusicPlaying(): boolean;
		getMusicTime(): number;
		setAudioTime(time: number): void;
		getAudioTime(): number;
		preloadAudio(path: string): void;
		startAudio(path: string, looped?: boolean): GrandTheftMultiplayer.Client.Javascript.SoundEvent;
		pauseAudio(ev?: GrandTheftMultiplayer.Client.Javascript.SoundEvent): void;
		resumeAudio(ev?: GrandTheftMultiplayer.Client.Javascript.SoundEvent): void;
		stopAudio(ev?: GrandTheftMultiplayer.Client.Javascript.SoundEvent): void;
		isAudioPlaying(ev?: GrandTheftMultiplayer.Client.Javascript.SoundEvent): boolean;
		setGameVolume(vol: number): void;
		setAudioVolume(vol: number): void;
		isAudioInitialized(): boolean;
		playSoundFrontEnd(soundName: string, soundSetName: string): void;
		createCamera(position: GrandTheftMultiplayer.Shared.Math.Vector3, rotation: GrandTheftMultiplayer.Shared.Math.Vector3): GrandTheftMultiplayer.Client.Javascript.GlobalCamera;
		setActiveCamera(camera: GrandTheftMultiplayer.Client.Javascript.GlobalCamera): void;
		setGameplayCameraActive(): void;
		getActiveCamera(): GrandTheftMultiplayer.Client.Javascript.GlobalCamera;
		setCameraShake(cam: GrandTheftMultiplayer.Client.Javascript.GlobalCamera, shakeType: string, amplitute: number): void;
		stopCameraShake(cam: GrandTheftMultiplayer.Client.Javascript.GlobalCamera): void;
		isCameraShaking(cam: GrandTheftMultiplayer.Client.Javascript.GlobalCamera): boolean;
		setGameplayCameraShake(shakeType: string, amplitute: number): void;
		stopGameplayCameraShake(): void;
		isGameplayCameraShaking(): boolean;
		setCameraBehindPlayer(): void;
		setCameraPosition(cam: GrandTheftMultiplayer.Client.Javascript.GlobalCamera, pos: GrandTheftMultiplayer.Shared.Math.Vector3): void;
		getCameraPosition(cam: GrandTheftMultiplayer.Client.Javascript.GlobalCamera): GrandTheftMultiplayer.Shared.Math.Vector3;
		setCameraRotation(cam: GrandTheftMultiplayer.Client.Javascript.GlobalCamera, rotation: GrandTheftMultiplayer.Shared.Math.Vector3): void;
		getCameraRotation(cam: GrandTheftMultiplayer.Client.Javascript.GlobalCamera): GrandTheftMultiplayer.Shared.Math.Vector3;
		setCameraFov(cam: GrandTheftMultiplayer.Client.Javascript.GlobalCamera, fov: number): void;
		getCameraFov(cam: GrandTheftMultiplayer.Client.Javascript.GlobalCamera): number;
		pointCameraAtPosition(cam: GrandTheftMultiplayer.Client.Javascript.GlobalCamera, pos: GrandTheftMultiplayer.Shared.Math.Vector3): void;
		pointCameraAtEntity(cam: GrandTheftMultiplayer.Client.Javascript.GlobalCamera, ent: GrandTheftMultiplayer.Client.Models.LocalHandle, offset: GrandTheftMultiplayer.Shared.Math.Vector3): void;
		pointCameraAtEntityBone(cam: GrandTheftMultiplayer.Client.Javascript.GlobalCamera, ent: GrandTheftMultiplayer.Client.Models.LocalHandle, bone: number, offset: GrandTheftMultiplayer.Shared.Math.Vector3): void;
		stopCameraPointing(cam: GrandTheftMultiplayer.Client.Javascript.GlobalCamera): void;
		attachCameraToEntity(cam: GrandTheftMultiplayer.Client.Javascript.GlobalCamera, ent: GrandTheftMultiplayer.Client.Models.LocalHandle, offset: GrandTheftMultiplayer.Shared.Math.Vector3): void;
		attachCameraToEntityBone(cam: GrandTheftMultiplayer.Client.Javascript.GlobalCamera, ent: GrandTheftMultiplayer.Client.Models.LocalHandle, bone: number, offset: GrandTheftMultiplayer.Shared.Math.Vector3): void;
		detachCamera(cam: GrandTheftMultiplayer.Client.Javascript.GlobalCamera): void;
		interpolateCameras(from: GrandTheftMultiplayer.Client.Javascript.GlobalCamera, to: GrandTheftMultiplayer.Client.Javascript.GlobalCamera, duration: number, easepos: boolean, easerot: boolean): void;
		getGameplayCamPos(): GrandTheftMultiplayer.Shared.Math.Vector3;
		getGameplayCamRot(): GrandTheftMultiplayer.Shared.Math.Vector3;
		getGameplayCamDir(): GrandTheftMultiplayer.Shared.Math.Vector3;
		createCefBrowser(width: number, height: number, local?: boolean): GrandTheftMultiplayer.Client.GUI.Browser;
		destroyCefBrowser(browser: GrandTheftMultiplayer.Client.GUI.Browser): void;
		isCefBrowserInitialized(browser: GrandTheftMultiplayer.Client.GUI.Browser): boolean;
		waitUntilCefBrowserInit(browser: GrandTheftMultiplayer.Client.GUI.Browser): void;
		waitUntilCefBrowserLoaded(browser: GrandTheftMultiplayer.Client.GUI.Browser): void;
		setCefBrowserSize(browser: GrandTheftMultiplayer.Client.GUI.Browser, width: number, height: number): void;
		getCefBrowserSize(browser: GrandTheftMultiplayer.Client.GUI.Browser): System.Drawing.Size;
		setCefBrowserHeadless(browser: GrandTheftMultiplayer.Client.GUI.Browser, headless: boolean): void;
		getCefBrowserHeadless(browser: GrandTheftMultiplayer.Client.GUI.Browser): boolean;
		setCefBrowserPosition(browser: GrandTheftMultiplayer.Client.GUI.Browser, xPos: number, yPos: number): void;
		getCefBrowserPosition(browser: GrandTheftMultiplayer.Client.GUI.Browser): System.Drawing.Point;
		loadPageCefBrowser(browser: GrandTheftMultiplayer.Client.GUI.Browser, uri: string, noCache?: boolean): void;
		loadHtmlCefBrowser(browser: GrandTheftMultiplayer.Client.GUI.Browser, html: string): void;
		getCurrentCefBrowserPageUrl(browser: GrandTheftMultiplayer.Client.GUI.Browser): string;
		goBackCefBrowser(browser: GrandTheftMultiplayer.Client.GUI.Browser): void;
		isCefBrowserLoading(browser: GrandTheftMultiplayer.Client.GUI.Browser): boolean;
		setCefDrawState(state: boolean): void;
		setCefFramerate(browser: GrandTheftMultiplayer.Client.GUI.Browser, fps: number): void;
		setCefBrowserFocus(browser: GrandTheftMultiplayer.Client.GUI.Browser, focus: boolean): void;
		isCefDrawEnabled(): boolean;
		pinCefBrowser(browser: GrandTheftMultiplayer.Client.GUI.Browser, x1: number, y1: number, x2: number, y2: number, x3: number, y3: number, x4: number, y4: number): void;
		clearCefPinning(browser: GrandTheftMultiplayer.Client.GUI.Browser): void;
		getBytesSentPerSecond(): number;
		getBytesReceivedPerSecond(): number;
		isControlJustPressed(control: number): boolean;
		isControlPressed(control: number): boolean;
		isDisabledControlJustReleased(control: number): boolean;
		isDisabledControlJustPressed(control: number): boolean;
		isDisabledControlPressed(control: number): boolean;
		isControlJustReleased(control: number): boolean;
		disableControlThisFrame(control: number): void;
		enableControlThisFrame(control: number): void;
		disableAllControlsThisFrame(): void;
		getControlNormal(control: number): number;
		getDisabledControlNormal(control: number): number;
		setControlNormal(control: number, value: number): void;
		drawLine(start: GrandTheftMultiplayer.Shared.Math.Vector3, end: GrandTheftMultiplayer.Shared.Math.Vector3, a: number, r: number, g: number, b: number): void;
		drawGameTexture(dict: string, txtName: string, x: number, y: number, width: number, height: number, heading: number, r: number, g: number, b: number, alpha: number): void;
		drawRectangle(xPos: number, yPos: number, wSize: number, hSize: number, r: number, g: number, b: number, alpha: number): void;
		drawText(caption: string, xPos: number, yPos: number, scale: number, r: number, g: number, b: number, alpha: number, font: number, justify: number, shadow: boolean, outline: boolean, wordWrap: number): void;
		addTextElement(caption: string, x: number, y: number, scale: number, r: number, g: number, b: number, a: number, font: number, alignment: number): NativeUI.UIResText;
		dxDrawTexture(path: string, pos: System.Drawing.Point, size: System.Drawing.Size, rotation?: number): void;
		getFontWidth(text: string, font: number, scale: number): number;
		createParticleEffectOnPosition(ptfxLibrary: string, ptfxName: string, position: GrandTheftMultiplayer.Shared.Math.Vector3, rotation: GrandTheftMultiplayer.Shared.Math.Vector3, scale: number): void;
		createParticleEffectOnEntity(ptfxLibrary: string, ptfxName: string, entity: GrandTheftMultiplayer.Client.Models.LocalHandle, offset: GrandTheftMultiplayer.Shared.Math.Vector3, rotation: GrandTheftMultiplayer.Shared.Math.Vector3, scale: number, boneIndex?: number): void;
		createExplosion(explosionType: number, position: GrandTheftMultiplayer.Shared.Math.Vector3, damageScale: number): void;
		createOwnedExplosion(owner: GrandTheftMultiplayer.Client.Models.LocalHandle, explosionType: number, position: GrandTheftMultiplayer.Shared.Math.Vector3, damageScale: number): void;
		deleteEntity(handle: GrandTheftMultiplayer.Client.Models.LocalHandle): void;
		setEntityPosition(ent: GrandTheftMultiplayer.Client.Models.LocalHandle, pos: GrandTheftMultiplayer.Shared.Math.Vector3, ground?: boolean): void;
		getEntityPosition(entity: GrandTheftMultiplayer.Client.Models.LocalHandle): GrandTheftMultiplayer.Shared.Math.Vector3;
		setEntityRotation(ent: GrandTheftMultiplayer.Client.Models.LocalHandle, rot: GrandTheftMultiplayer.Shared.Math.Vector3): void;
		setEntityQuaternion(entity: GrandTheftMultiplayer.Client.Models.LocalHandle, x: number, y: number, z: number, w: number): void;
		getEntityQuaternion(entity: GrandTheftMultiplayer.Client.Models.LocalHandle): GTA.Math.Quaternion;
		getEntityRotation(entity: GrandTheftMultiplayer.Client.Models.LocalHandle): GrandTheftMultiplayer.Shared.Math.Vector3;
		getEntityLeftPosition(entity: GrandTheftMultiplayer.Client.Models.LocalHandle): GrandTheftMultiplayer.Shared.Math.Vector3;
		getEntityRightPosition(entity: GrandTheftMultiplayer.Client.Models.LocalHandle): GrandTheftMultiplayer.Shared.Math.Vector3;
		getEntityFrontPosition(entity: GrandTheftMultiplayer.Client.Models.LocalHandle): GrandTheftMultiplayer.Shared.Math.Vector3;
		getEntityRearPosition(entity: GrandTheftMultiplayer.Client.Models.LocalHandle): GrandTheftMultiplayer.Shared.Math.Vector3;
		getEntityAbovePosition(entity: GrandTheftMultiplayer.Client.Models.LocalHandle): GrandTheftMultiplayer.Shared.Math.Vector3;
		getEntityBelowPosition(entity: GrandTheftMultiplayer.Client.Models.LocalHandle): GrandTheftMultiplayer.Shared.Math.Vector3;
		setEntityVelocity(entity: GrandTheftMultiplayer.Client.Models.LocalHandle, velocity: GrandTheftMultiplayer.Shared.Math.Vector3): void;
		getEntityVelocity(entity: GrandTheftMultiplayer.Client.Models.LocalHandle): GrandTheftMultiplayer.Shared.Math.Vector3;
		setEntityTransparency(entity: GrandTheftMultiplayer.Client.Models.LocalHandle, alpha: number): void;
		getEntityTransparency(entity: GrandTheftMultiplayer.Client.Models.LocalHandle): number;
		getEntityType(entity: GrandTheftMultiplayer.Client.Models.LocalHandle): number;
		setEntityDimension(entity: GrandTheftMultiplayer.Client.Models.LocalHandle, dimension: number): void;
		getEntityDimension(entity: GrandTheftMultiplayer.Client.Models.LocalHandle): number;
		getEntityModel(entity: GrandTheftMultiplayer.Client.Models.LocalHandle): number;
		doesEntityExist(entity: GrandTheftMultiplayer.Client.Models.LocalHandle): boolean;
		setEntityInvincible(entity: GrandTheftMultiplayer.Client.Models.LocalHandle, invincible: boolean): void;
		getEntityInvincible(entity: GrandTheftMultiplayer.Client.Models.LocalHandle): boolean;
		isEntityTouchingModel(entity: GrandTheftMultiplayer.Client.Models.LocalHandle, modelHash: number): boolean;
		isEntityTouchingEntity(entity: GrandTheftMultiplayer.Client.Models.LocalHandle, targetEntity: GrandTheftMultiplayer.Client.Models.LocalHandle): boolean;
		isEntityUpright(entity: GrandTheftMultiplayer.Client.Models.LocalHandle, angle: number): boolean;
		isEntityUpsidedown(entity: GrandTheftMultiplayer.Client.Models.LocalHandle): boolean;
		getEntityBoneCount(entity: GrandTheftMultiplayer.Client.Models.LocalHandle): number;
		hasEntityBone(entity: GrandTheftMultiplayer.Client.Models.LocalHandle, boneName: string): boolean;
		getEntityBoneIndexByName(entity: GrandTheftMultiplayer.Client.Models.LocalHandle, boneName: string): number;
		getEntityBoneWorldPosition(entity: GrandTheftMultiplayer.Client.Models.LocalHandle, boneName: string): GrandTheftMultiplayer.Shared.Math.Vector3;
		getEntityBoneWorldPosition(entity: GrandTheftMultiplayer.Client.Models.LocalHandle, boneIndex: number): GrandTheftMultiplayer.Shared.Math.Vector3;
		getEntityBoneRelativePosition(entity: GrandTheftMultiplayer.Client.Models.LocalHandle, boneName: string): GrandTheftMultiplayer.Shared.Math.Vector3;
		getEntityBoneRelativePosition(entity: GrandTheftMultiplayer.Client.Models.LocalHandle, boneIndex: number): GrandTheftMultiplayer.Shared.Math.Vector3;
		getEntityHasCollided(entity: GrandTheftMultiplayer.Client.Models.LocalHandle): boolean;
		setEntityCollisionless(entity: GrandTheftMultiplayer.Client.Models.LocalHandle, status: boolean): void;
		getEntityCollisionless(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle): boolean;
		setEntityPositionFrozen(entity: GrandTheftMultiplayer.Client.Models.LocalHandle, frozen: boolean): void;
		isEntityPositionFrozen(entity: GrandTheftMultiplayer.Client.Models.LocalHandle): boolean;
		isEntityOnScreen(entity: GrandTheftMultiplayer.Client.Models.LocalHandle): boolean;
		attachEntity(ent1: GrandTheftMultiplayer.Client.Models.LocalHandle, ent2: GrandTheftMultiplayer.Client.Models.LocalHandle, bone: string, positionOffset: GrandTheftMultiplayer.Shared.Math.Vector3, rotationOffset: GrandTheftMultiplayer.Shared.Math.Vector3): void;
		detachEntity(ent: GrandTheftMultiplayer.Client.Models.LocalHandle): void;
		isEntityAttachedToAnything(ent: GrandTheftMultiplayer.Client.Models.LocalHandle): boolean;
		isEntityAttachedToEntity(from: GrandTheftMultiplayer.Client.Models.LocalHandle, to: GrandTheftMultiplayer.Client.Models.LocalHandle): boolean;
		isInRangeOf(entity: GrandTheftMultiplayer.Shared.Math.Vector3, destination: GrandTheftMultiplayer.Shared.Math.Vector3, range: number): boolean;
		vehicleNameToModel(modelName: string): number;
		pedNameToModel(modelName: string): number;
		pickupNameToModel(modelName: string): number;
		weaponNameToModel(modelName: string): number;
		isPed(ent: GrandTheftMultiplayer.Client.Models.LocalHandle): boolean;
		isVehicle(ent: GrandTheftMultiplayer.Client.Models.LocalHandle): boolean;
		isProp(ent: GrandTheftMultiplayer.Client.Models.LocalHandle): boolean;
		isEntityDead(ent: GrandTheftMultiplayer.Client.Models.LocalHandle): boolean;
		setEntitySyncedData(entity: GrandTheftMultiplayer.Client.Models.LocalHandle, key: string, data: any): boolean;
		resetEntitySyncedData(entity: GrandTheftMultiplayer.Client.Models.LocalHandle, key: string): void;
		hasEntitySyncedData(entity: GrandTheftMultiplayer.Client.Models.LocalHandle, key: string): boolean;
		getEntitySyncedData(entity: GrandTheftMultiplayer.Client.Models.LocalHandle, key: string): any;
		getAllEntitySyncedData(entity: GrandTheftMultiplayer.Client.Models.LocalHandle): System.Array<any>;
		setWorldSyncedData(key: string, data: any): boolean;
		resetWorldSyncedData(key: string): void;
		hasWorldSyncedData(key: string): boolean;
		getWorldSyncedData(key: string): any;
		getAllWorldSyncedData(): System.Array<any>;
		createBlip(pos: GrandTheftMultiplayer.Shared.Math.Vector3): GrandTheftMultiplayer.Client.Models.LocalHandle;
		setBlipPosition(blip: GrandTheftMultiplayer.Client.Models.LocalHandle, pos: GrandTheftMultiplayer.Shared.Math.Vector3): void;
		getBlipPosition(blip: GrandTheftMultiplayer.Client.Models.LocalHandle): GrandTheftMultiplayer.Shared.Math.Vector3;
		setBlipColor(blip: GrandTheftMultiplayer.Client.Models.LocalHandle, color: number): void;
		getBlipColor(blip: GrandTheftMultiplayer.Client.Models.LocalHandle): number;
		setBlipSprite(blip: GrandTheftMultiplayer.Client.Models.LocalHandle, sprite: number): void;
		getBlipSprite(blip: GrandTheftMultiplayer.Client.Models.LocalHandle): number;
		setBlipName(blip: GrandTheftMultiplayer.Client.Models.LocalHandle, name: string): void;
		getBlipName(blip: GrandTheftMultiplayer.Client.Models.LocalHandle): string;
		isBlipOnMinimap(blip: GrandTheftMultiplayer.Client.Models.LocalHandle): boolean;
		setBlipTransparency(blip: GrandTheftMultiplayer.Client.Models.LocalHandle, alpha: number): void;
		getBlipTransparency(blip: GrandTheftMultiplayer.Client.Models.LocalHandle): number;
		setBlipShortRange(blip: GrandTheftMultiplayer.Client.Models.LocalHandle, shortRange: boolean): void;
		getBlipShortRange(blip: GrandTheftMultiplayer.Client.Models.LocalHandle): boolean;
		showBlipRoute(blip: GrandTheftMultiplayer.Client.Models.LocalHandle, show: boolean): void;
		setBlipScale(blip: GrandTheftMultiplayer.Client.Models.LocalHandle, scale: number): void;
		getBlipScale(blip: GrandTheftMultiplayer.Client.Models.LocalHandle): number;
		setBlipRouteVisible(blip: GrandTheftMultiplayer.Client.Models.LocalHandle, visible: boolean): void;
		getBlipRouteVisible(blip: GrandTheftMultiplayer.Client.Models.LocalHandle): boolean;
		setBlipRouteColor(blip: GrandTheftMultiplayer.Client.Models.LocalHandle, color: number): void;
		getBlipRouteColor(blip: GrandTheftMultiplayer.Client.Models.LocalHandle): number;
		setBlipFlashing(blip: GrandTheftMultiplayer.Client.Models.LocalHandle, flashing: boolean): void;
		getBlipFlashing(blip: GrandTheftMultiplayer.Client.Models.LocalHandle): boolean;
		createMarker(markerType: number, pos: GrandTheftMultiplayer.Shared.Math.Vector3, dir: GrandTheftMultiplayer.Shared.Math.Vector3, rot: GrandTheftMultiplayer.Shared.Math.Vector3, scale: GrandTheftMultiplayer.Shared.Math.Vector3, r: number, g: number, b: number, alpha: number): GrandTheftMultiplayer.Client.Models.LocalHandle;
		setMarkerType(marker: GrandTheftMultiplayer.Client.Models.LocalHandle, type: number): void;
		getMarkerType(marker: GrandTheftMultiplayer.Client.Models.LocalHandle): number;
		setMarkerColor(marker: GrandTheftMultiplayer.Client.Models.LocalHandle, alpha: number, r: number, g: number, b: number): void;
		getMarkerColor(marker: GrandTheftMultiplayer.Client.Models.LocalHandle): System.Drawing.Color;
		setMarkerScale(marker: GrandTheftMultiplayer.Client.Models.LocalHandle, scale: GrandTheftMultiplayer.Shared.Math.Vector3): void;
		getMarkerScale(marker: GrandTheftMultiplayer.Client.Models.LocalHandle): GrandTheftMultiplayer.Shared.Math.Vector3;
		setMarkerDirection(marker: GrandTheftMultiplayer.Client.Models.LocalHandle, dir: GrandTheftMultiplayer.Shared.Math.Vector3): void;
		getMarkerDirection(marker: GrandTheftMultiplayer.Client.Models.LocalHandle): GrandTheftMultiplayer.Shared.Math.Vector3;
		setMarkerBobUpAndDown(marker: GrandTheftMultiplayer.Client.Models.LocalHandle, bobUpAndDown: boolean): void;
		getMarkerBobUpAndDown(marker: GrandTheftMultiplayer.Client.Models.LocalHandle): boolean;
		createPed(model: number, pos: GrandTheftMultiplayer.Shared.Math.Vector3, rot: GrandTheftMultiplayer.Shared.Math.Vector3): GrandTheftMultiplayer.Client.Models.LocalHandle;
		createPed(model: number, pos: GrandTheftMultiplayer.Shared.Math.Vector3, heading: number): GrandTheftMultiplayer.Client.Models.LocalHandle;
		getBoneName(bone: number): string;
		getPedCanRagdoll(): boolean;
		setMaxHealth(maxHealth: number): void;
		getMaxHealth(): number;
		setPedCanRagdoll(canRagdoll: boolean): void;
		setPedToRagdoll(duration?: number, ragdollType?: number): void;
		cancelPedRagdoll(): void;
		registerPedHeadShot(player: GrandTheftMultiplayer.Client.Models.LocalHandle): number;
		unregisterPedHeadShot(player: GrandTheftMultiplayer.Client.Models.LocalHandle): void;
		getPedHeadShotTextureString(handle: number): string;
		isPedHeadShotReady(handle: number): boolean;
		isPedHeadShotValid(handle: number): boolean;
		createTextLabel(text: string, pos: GrandTheftMultiplayer.Shared.Math.Vector3, range: number, size: number, entitySeethrough?: boolean): GrandTheftMultiplayer.Client.Models.LocalHandle;
		setTextLabelText(label: GrandTheftMultiplayer.Client.Models.LocalHandle, text: string): void;
		setTextLabelColor(textLabel: GrandTheftMultiplayer.Client.Models.LocalHandle, alpha: number, r: number, g: number, b: number): void;
		getTextLabelColor(textLabel: GrandTheftMultiplayer.Client.Models.LocalHandle): System.Drawing.Color;
		setTextLabelSeethrough(handle: GrandTheftMultiplayer.Client.Models.LocalHandle, seethrough: boolean): void;
		getTextLabelSeethrough(handle: GrandTheftMultiplayer.Client.Models.LocalHandle): boolean;
		createVehicle(model: number, pos: GrandTheftMultiplayer.Shared.Math.Vector3, rot: GrandTheftMultiplayer.Shared.Math.Vector3): GrandTheftMultiplayer.Client.Models.LocalHandle;
		setVehicleLivery(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle, livery: number): void;
		getVehicleLivery(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle): number;
		setVehicleLocked(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle, locked: boolean): void;
		getVehicleLocked(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle): boolean;
		getVehicleTrailer(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle): GrandTheftMultiplayer.Client.Models.LocalHandle;
		getVehicleTraileredBy(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle): GrandTheftMultiplayer.Client.Models.LocalHandle;
		getVehicleSirenState(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle): boolean;
		isVehicleTyrePopped(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle, tyre: number): boolean;
		popVehicleTyre(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle, tyre: number, pop: boolean): void;
		isVehicleDoorBroken(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle, door: number): boolean;
		setVehicleDoorState(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle, door: number, open: boolean): void;
		getVehicleModSlotName(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle, modType: number): string;
		getVehicleModTextLabel(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle, modType: number, modValue: number): string;
		getVehicleLiveryName(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle, liveryIndex: number): string;
		getVehicleDoorState(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle, door: number): boolean;
		breakVehicleDoor(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle, door: number, breakDoor: boolean): void;
		isVehicleWindowBroken(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle, window: number): boolean;
		breakVehicleWindow(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle, window: number, breakWindow: boolean): void;
		setVehicleExtra(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle, slot: number, enabled: boolean): void;
		getVehicleExtra(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle, slot: number): boolean;
		setVehicleNumberPlate(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle, plate: string): void;
		getVehicleNumberPlate(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle): string;
		setVehicleEngineStatus(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle, turnedOn: boolean): void;
		getVehicleEngineStatus(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle): boolean;
		setVehicleSpecialLightStatus(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle, status: boolean): void;
		getVehicleSpecialLightStatus(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle): boolean;
		setVehicleMod(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle, modType: number, mod: number): void;
		getVehicleNumModCount(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle, modType: number): number;
		hasVehicleMod(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle, modType: number): boolean;
		getVehicleMod(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle, modType: number): number;
		getVehicleEngineTemperature(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle): number;
		getVehicleTurbo(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle): number;
		getVehicleClutch(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle): number;
		getVehicleThrottle(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle): number;
		getVehicleThrottlePower(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle): number;
		getVehicleBrakePower(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle): number;
		setVehicleOilLevel(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle, oilLevel: number): void;
		getVehicleOilLevel(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle): number;
		setVehicleFuelLevel(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle, fuelLevel: number): void;
		getVehicleFuelLevel(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle): number;
		setVehicleDirtLevel(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle, dirtLevel: number): void;
		getVehicleDirtLevel(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle): number;
		removeVehicleMod(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle, modType: number): void;
		setVehicleLightsMode(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle, mode: number): void;
		setVehicleBulletproofTyres(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle, bulletproof: boolean): void;
		getVehicleBulletproofTyres(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle): boolean;
		setVehicleNumberPlateStyle(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle, style: number): void;
		getVehicleNumberPlateStyle(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle): number;
		setVehiclePearlescentColor(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle, color: number): void;
		getVehiclePearlescentColor(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle): number;
		setVehicleWheelColor(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle, color: number): void;
		getVehicleWheelColor(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle): number;
		setVehicleWheelType(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle, type: number): void;
		getVehicleWheelType(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle): number;
		setVehicleModColor1(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle, r: number, g: number, b: number): void;
		setVehicleModColor2(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle, r: number, g: number, b: number): void;
		setVehicleTyreSmokeColor(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle, r: number, g: number, b: number): void;
		setVehicleWindowTint(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle, type: number): void;
		getVehicleWindowTint(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle): number;
		toggleVehicleGrip(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle, enabled: boolean): void;
		setVehicleEnginePowerMultiplier(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle, mult: number): void;
		getVehicleEnginePowerMultiplier(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle): number;
		setVehicleEngineTorqueMultiplier(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle, mult: number): void;
		getVehicleEngineTorqueMultiplier(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle): number;
		setVehicleNeonState(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle, slot: number, turnedOn: boolean): void;
		getVehicleNeonState(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle, slot: number): boolean;
		setVehicleNeonColor(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle, r: number, g: number, b: number): void;
		getVehicleNeonColor(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle): System.Drawing.Color;
		setVehicleDashboardColor(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle, type: number): void;
		getVehicleDashboardColor(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle): number;
		setVehicleTrimColor(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle, type: number): void;
		getVehicleTrimColor(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle): number;
		getVehicleDisplayName(model: number): string;
		getVehicleMaxSpeed(model: number): number;
		getVehicleMaxBraking(model: number): number;
		getVehicleMaxTraction(model: number): number;
		getVehicleMaxAcceleration(model: number): number;
		getVehicleMaxOccupants(model: number): number;
		getVehicleClass(model: number): number;
		setVehiclePrimaryColor(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle, color: number): void;
		setVehicleSecondaryColor(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle, color: number): void;
		setVehicleCustomPrimaryColor(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle, r: number, g: number, b: number): void;
		setVehicleCustomSecondaryColor(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle, r: number, g: number, b: number): void;
		getVehicleCustomPrimaryColor(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle): System.Drawing.Color;
		getVehicleCustomSecondaryColor(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle): System.Drawing.Color;
		getVehiclePrimaryColor(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle): number;
		getVehicleSecondaryColor(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle): number;
		getVehicleHealth(entity: GrandTheftMultiplayer.Client.Models.LocalHandle): number;
		getVehiclePetrolTankHealth(entity: GrandTheftMultiplayer.Client.Models.LocalHandle): number;
		getVehicleRPM(entity: GrandTheftMultiplayer.Client.Models.LocalHandle): number;
		getVehicleHighGear(entity: GrandTheftMultiplayer.Client.Models.LocalHandle): number;
		getVehicleCurrentGear(entity: GrandTheftMultiplayer.Client.Models.LocalHandle): number;
		explodeVehicle(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle): void;
		getVehicleModelName(model: number): string;
		registerChatOverride(): GrandTheftMultiplayer.Client.Javascript.JavascriptChat;
		setCanOpenChat(show: boolean): void;
		getCanOpenChat(): boolean;
		setChatVisible(display: boolean): void;
		getChatVisible(): boolean;
		toggleAlternativeVersionLabelPosition(toggle: boolean): void;
		getAlternativeVersionLabelPositionActive(): boolean;
		setShowWastedScreenOnDeath(enabled: boolean): void;
		getShowWastedScreenOnDeath(): boolean;
		disableVehicleEnteringKeys(enabled: boolean): void;
		getVehicleEnteringKeysDisabled(): boolean;
		disableAlternativeMainMenuKey(enabled: boolean): void;
		getAlternativeMainMenuKeyDisabled(): boolean;
		isChatOpen(): boolean;
		setUiColor(r: number, g: number, b: number): void;
		sendChatMessage(sender: string, text: string): void;
		sendChatMessage(text: string): void;
		getScreenResolutionMantainRatio(): System.Drawing.SizeF;
		getScreenResolutionMaintainRatio(): System.Drawing.SizeF;
		getScreenResolution(): System.Drawing.Size;
		sendNotification(text: string): void;
		sendPictureNotification(body: string, pic: string, flash: number, iconType: number, sender: string, subject: string): void;
		displaySubtitle(text: string): void;
		displaySubtitle(text: string, duration: number): void;
		displayHelpTextThisFrame(text: string): void;
		showShard(text: string, timeout?: number): void;
		showColorShard(text: string, description: string, color1: number, color2: number, time?: number): void;
		showWeaponPurchasedShard(text: string, weaponName: string, weapon: number, time?: number): void;
		getWaypointPosition(): GrandTheftMultiplayer.Shared.Math.Vector3;
		isWaypointSet(): boolean;
		setWaypoint(x: number, y: number): void;
		removeWaypoint(): void;
		setHudVisible(visible: boolean): void;
		getHudVisible(): boolean;
		createMenu(subtitle: string, x: number, y: number, anchor: number): NativeUI.UIMenu;
		createMenu(title: string, subtitle: string, x: number, y: number, anchor: number, enableBanner?: boolean): NativeUI.UIMenu;
		createMenuItem(label: string, description: string): NativeUI.UIMenuItem;
		createColoredItem(label: string, description: string, hexColor: string, hexHighlightColor: string): NativeUI.UIMenuColoredItem;
		createCheckboxItem(label: string, description: string, isChecked: boolean): NativeUI.UIMenuCheckboxItem;
		createListItem(label: string, description: string, items: System.Collections.Generic.List<string>, index: number): NativeUI.UIMenuListItem;
		createDynamicListItem(label: string, description: string, startingItem: string): NativeUI.UIMenuDynamicListItem;
		getMenuPool(): GrandTheftMultiplayer.Client.Javascript.MenuPoolWrapper;
		drawMenu(menu: NativeUI.UIMenu): void;
		addSubMenu(menu: NativeUI.UIMenu, text: string): NativeUI.UIMenu;
		addSubMenu(menu: NativeUI.UIMenu, text: string, description: string): NativeUI.UIMenu;
		addSubMenu(menu: NativeUI.UIMenu, subMenu: NativeUI.UIMenu, text: string): NativeUI.UIMenu;
		addSubMenu(menu: NativeUI.UIMenu, subMenu: NativeUI.UIMenu, text: string, description: string): NativeUI.UIMenu;
		addSubMenu(menu: NativeUI.UIMenu, text: string, UseParentXY: boolean): NativeUI.UIMenu;
		addSubMenu(menu: NativeUI.UIMenu, text: string, description: string, UseParentXY: boolean): NativeUI.UIMenu;
		addSubMenu(menu: NativeUI.UIMenu, text: string, description: string, x: number, y: number, anchor: number): NativeUI.UIMenu;
		setMenuBannerSprite(menu: NativeUI.UIMenu, spritedict: string, spritename: string): void;
		setMenuBannerTexture(menu: NativeUI.UIMenu, path: string): void;
		setMenuBannerRectangle(menu: NativeUI.UIMenu, alpha: number, red: number, green: number, blue: number): void;
		setMenuTitle(menu: NativeUI.UIMenu, title: string): void;
		setMenuSubtitle(menu: NativeUI.UIMenu, text: string): void;
		getUserInput(defaultText: string, maxlen: number): string;
		isAnyMenuOpen(): boolean;
		closeAllMenus(): void;
		requestScaleform(scaleformName: string): GTA.Scaleform;
		renderScaleform(sc: GTA.Scaleform, x: number, y: number, w: number, h: number): void;
		playScreenEffect(effectName: string, duration: number, looped: boolean): void;
		stopScreenEffect(effectName: string): void;
		stopAllScreenEffects(): void;
		lerpVector(start: GrandTheftMultiplayer.Shared.Math.Vector3, end: GrandTheftMultiplayer.Shared.Math.Vector3, currentTime: number, duration: number): GrandTheftMultiplayer.Shared.Math.Vector3;
		lerpFloat(start: number, end: number, currentTime: number, duration: number): number;
		angleBetween(from: GrandTheftMultiplayer.Shared.Math.Vector3, to: GrandTheftMultiplayer.Shared.Math.Vector3): number;
		loadModel(model: number): void;
		getModelDimensions(model: number): GrandTheftMultiplayer.Client.Models.ModelDimensions;
		callNative(hash: string, ...args: any[]): void;
		returnNative(hash: string, returnType: number, ...args: any[]): any;
		disconnect(reason: string): void;
		forceSendAimData(force: boolean): void;
		isAimDataForced(): boolean;
		isInFirstPersonCam(player: GrandTheftMultiplayer.Client.Models.LocalHandle): boolean;
		disableFingerPointing(disabled: boolean): void;
		isFingerPointingDisabled(): boolean;
		setFingerPointing(enabled: boolean): void;
		isFingerPointing(): boolean;
		isSpectating(): boolean;
		getUniqueHardwareId(): string;
		getSocialClubName(): string;
		getGamePlayer(): number;
		getLocalPlayer(): GrandTheftMultiplayer.Client.Models.LocalHandle;
		getLocalPlayerInvincible(): boolean;
		detonatePlayerStickies(): void;
		setPlayerNametag(player: GrandTheftMultiplayer.Client.Models.LocalHandle, text: string): void;
		resetPlayerNametag(player: GrandTheftMultiplayer.Client.Models.LocalHandle): void;
		setPlayerNametagVisible(player: GrandTheftMultiplayer.Client.Models.LocalHandle, show: boolean): void;
		getPlayerNametagVisible(player: GrandTheftMultiplayer.Client.Models.LocalHandle): boolean;
		setPlayerHealthbarVisible(player: GrandTheftMultiplayer.Client.Models.LocalHandle, show: boolean): void;
		getPlayerHealthbarVisible(player: GrandTheftMultiplayer.Client.Models.LocalHandle): boolean;
		setPlayerArmorbarVisible(player: GrandTheftMultiplayer.Client.Models.LocalHandle, show: boolean): void;
		getPlayerArmorbarVisible(player: GrandTheftMultiplayer.Client.Models.LocalHandle): boolean;
		setPlayerNametagColor(player: GrandTheftMultiplayer.Client.Models.LocalHandle, r: number, g: number, b: number): void;
		resetPlayerNametagColor(player: GrandTheftMultiplayer.Client.Models.LocalHandle): void;
		isPlayerInAnyVehicle(player: GrandTheftMultiplayer.Client.Models.LocalHandle): boolean;
		isPlayerOnFire(player: GrandTheftMultiplayer.Client.Models.LocalHandle): boolean;
		isPlayerParachuting(player: GrandTheftMultiplayer.Client.Models.LocalHandle): boolean;
		isPlayerInFreefall(player: GrandTheftMultiplayer.Client.Models.LocalHandle): boolean;
		isPlayerAiming(player: GrandTheftMultiplayer.Client.Models.LocalHandle): boolean;
		isPlayerShooting(player: GrandTheftMultiplayer.Client.Models.LocalHandle): boolean;
		isPlayerReloading(player: GrandTheftMultiplayer.Client.Models.LocalHandle): boolean;
		isPlayerInCover(player: GrandTheftMultiplayer.Client.Models.LocalHandle): boolean;
		isPlayerOnLadder(player: GrandTheftMultiplayer.Client.Models.LocalHandle): boolean;
		isPlayerRagdoll(player: GrandTheftMultiplayer.Client.Models.LocalHandle): boolean;
		isPlayerWearingHelmet(player: GrandTheftMultiplayer.Client.Models.LocalHandle): boolean;
		isPlayerDiving(player: GrandTheftMultiplayer.Client.Models.LocalHandle): boolean;
		isPlayerSwimming(player: GrandTheftMultiplayer.Client.Models.LocalHandle): boolean;
		isPlayerSwimmingUnderWater(player: GrandTheftMultiplayer.Client.Models.LocalHandle): boolean;
		isPlayerFalling(player: GrandTheftMultiplayer.Client.Models.LocalHandle): boolean;
		isPlayerClimbing(player: GrandTheftMultiplayer.Client.Models.LocalHandle): boolean;
		getPlayerAimingPoint(player: GrandTheftMultiplayer.Client.Models.LocalHandle): GrandTheftMultiplayer.Shared.Math.Vector3;
		isPlayerDead(player: GrandTheftMultiplayer.Client.Models.LocalHandle): boolean;
		setPlayerSkin(model: number): void;
		setPlayerDefaultClothes(): void;
		setPlayerTeam(team: number): void;
		getPlayerTeam(): number;
		playPlayerScenario(name: string): void;
		playPlayerScenario(name: string, playEnterAnim: boolean): void;
		playPlayerAnimation(animDict: string, animName: string, flag: number, duration?: number): void;
		stopPlayerAnimation(): void;
		setPlayerComponentVariation(player: GrandTheftMultiplayer.Client.Models.LocalHandle, componentId: number, drawableId: number, textureId: number): void;
		setPlayerClothes(player: GrandTheftMultiplayer.Client.Models.LocalHandle, slot: number, drawable: number, texture: number): void;
		setPlayerAccessory(player: GrandTheftMultiplayer.Client.Models.LocalHandle, slot: number, drawable: number, texture: number): void;
		clearPlayerAccessory(player: GrandTheftMultiplayer.Client.Models.LocalHandle, slot: number): void;
		clearPlayerTasks(): void;
		setPlayerInvincible(invincible: boolean): void;
		setPlayerWantedLevel(wantedLevel: number): void;
		getPlayerWantedLevel(): number;
		getPlayerInvincible(): boolean;
		setPlayerArmor(armor: number): void;
		getPlayerArmor(player: GrandTheftMultiplayer.Client.Models.LocalHandle): number;
		getPlayerByName(name: string): GrandTheftMultiplayer.Client.Models.LocalHandle;
		getPlayerName(player: GrandTheftMultiplayer.Client.Models.LocalHandle): string;
		getPlayerVehicleSeatIndex(player: GrandTheftMultiplayer.Client.Models.LocalHandle): number;
		getPlayerVehicleSeat(player: GrandTheftMultiplayer.Client.Models.LocalHandle): number;
		getPlayerSeatbelt(player: GrandTheftMultiplayer.Client.Models.LocalHandle): boolean;
		setPlayerIntoVehicle(vehicle: GrandTheftMultiplayer.Client.Models.LocalHandle, seat: number): void;
		setPlayerHealth(health: number): void;
		getPlayerHealth(player: GrandTheftMultiplayer.Client.Models.LocalHandle): number;
		createPlayerNametag(player: GrandTheftMultiplayer.Client.Models.LocalHandle, nameTag: string): number;
		removePlayerNametag(nametagId: number): void;
		isPlayerNametagActive(nametagId: number): boolean;
		setPlayerNametagComponentVisibility(nametagId: number, component: number, toggle: boolean): void;
		setPlayerNametagFlagColor(nametagId: number, flag: number, color: number): void;
		setPlayerNametagFlagAlpha(nametagId: number, component: number, alpha: number): void;
		setPlayerNametagWantedLevel(nametagId: number, wantedlvl: number): void;
		setPlayerNametagChattingText(nametagId: number, chattingText: string): void;
		setPlayerNametagText(nametagId: number, nametag: string): void;
		setPlayerNametagHealthbarColor(nametagId: number, color: number): void;
		getPlayerAimCoords(player: GrandTheftMultiplayer.Client.Models.LocalHandle): GrandTheftMultiplayer.Shared.Math.Vector3;
		getPlayerPing(player: GrandTheftMultiplayer.Client.Models.LocalHandle): number;
		getPlayerVehicle(player: GrandTheftMultiplayer.Client.Models.LocalHandle): GrandTheftMultiplayer.Client.Models.LocalHandle;
		resetPlayerVisualDamage(player: GrandTheftMultiplayer.Client.Models.LocalHandle): void;
		clearPlayerBloodDamage(player: GrandTheftMultiplayer.Client.Models.LocalHandle): void;
		applyPlayerBlood(player: GrandTheftMultiplayer.Client.Models.LocalHandle, boneIndex: number, xRot: number, yRot: number, zRot: number, woundType: string): void;
		setPlayerHeadOverlay(player: GrandTheftMultiplayer.Client.Models.LocalHandle, overlayId: number, partIndex: number, opacity: number): void;
		getPlayerHeadOverlayValue(player: GrandTheftMultiplayer.Client.Models.LocalHandle, overlayId: number): number;
		setPlayerEyeColor(player: GrandTheftMultiplayer.Client.Models.LocalHandle, index: number): void;
		setPlayerHeadOverlayColor(player: GrandTheftMultiplayer.Client.Models.LocalHandle, overlayId: number, colorType: number, colorId: number, opacity: number): void;
		updatePlayerHeadBlendData(player: GrandTheftMultiplayer.Client.Models.LocalHandle, shapeMix: number, skinMix: number, thirdMix: number): void;
		setPlayerHeadBlendData(player: GrandTheftMultiplayer.Client.Models.LocalHandle, shapeFirstId: number, shapeSecondId: number, shapeThirdId: number, skinFirstId: number, skinSecondId: number, skinThirdId: number, shapeMix: number, skinMix: number, thirdMix: number, isParent: boolean): void;
		hasPlayerHeadBlendFinished(player: GrandTheftMultiplayer.Client.Models.LocalHandle): boolean;
		getFirstParentIdForPedType(type: number): number;
		setPlayerFaceFeature(player: GrandTheftMultiplayer.Client.Models.LocalHandle, index: number, scale: number): void;
		getNumHeadOverlayValues(overlayId: number): number;
		getNumHairColors(): number;
		getNumMakeupColors(): number;
		isPlayerHairColorValid(colorId: number): boolean;
		getTattooZone(collection: string, overlay: string): number;
		getTattooZone(collection: number, overlay: number): number;
		clearPlayerFacialDecorations(player: GrandTheftMultiplayer.Client.Models.LocalHandle): void;
		clearPlayerDecorations(player: GrandTheftMultiplayer.Client.Models.LocalHandle): void;
		isPlayerLipstickColorValid(colorId: number): boolean;
		isPlayerBlushColorValid(colorId: number): boolean;
		isPlayerClothesVariationValid(player: GrandTheftMultiplayer.Client.Models.LocalHandle, componentId: number, drawableId: number, textureId: number): boolean;
		isPlayerComponentVariationValid(player: GrandTheftMultiplayer.Client.Models.LocalHandle, slot: number, drawable: number, texture: number): boolean;
		isPlayerComponentPropValid(player: GrandTheftMultiplayer.Client.Models.LocalHandle, componentId: number, drawableId: number, textureId: number): boolean;
		setPlayerHairColor(player: GrandTheftMultiplayer.Client.Models.LocalHandle, hairColorId: number, hairHighlightId: number): void;
		setPlayerEyebrows(player: GrandTheftMultiplayer.Client.Models.LocalHandle, id: number, colorId: number, opacity: number): void;
		setPlayerChestHair(player: GrandTheftMultiplayer.Client.Models.LocalHandle, id: number, colorId: number, opacity: number): void;
		setPlayerFacePaint(player: GrandTheftMultiplayer.Client.Models.LocalHandle, id: number, opacity: number): void;
		setPlayerBeard(player: GrandTheftMultiplayer.Client.Models.LocalHandle, id: number, colorId: number, opacity: number): void;
		setPlayerHairStyle(player: GrandTheftMultiplayer.Client.Models.LocalHandle, id: number, colorId: number, highlightId: number, collection: string, overlay: string): void;
		setPlayerFacialDecoration(player: GrandTheftMultiplayer.Client.Models.LocalHandle, collection: string, overlay: string): void;
		setPlayerFacialDecoration(player: GrandTheftMultiplayer.Client.Models.LocalHandle, collection: number, overlay: number): void;
		setPlayerIsDrunk(player: GrandTheftMultiplayer.Client.Models.LocalHandle, isDrunk: boolean): void;
		setPlayerMovementClipset(player: GrandTheftMultiplayer.Client.Models.LocalHandle, animSet: string, speed: number): void;
		resetPlayerMovementClipset(player: GrandTheftMultiplayer.Client.Models.LocalHandle): void;
		applyPlayerDamagePack(player: GrandTheftMultiplayer.Client.Models.LocalHandle, damagePack: string, damage: number, mult: number): void;
		setPlayerFacialIdleAnimOverride(player: GrandTheftMultiplayer.Client.Models.LocalHandle, animName: string): void;
		clearPlayerFacialIdleAnimOverride(player: GrandTheftMultiplayer.Client.Models.LocalHandle): void;
		setPlayerWeaponAnimationOverride(player: GrandTheftMultiplayer.Client.Models.LocalHandle, animStyle: string): void;
		requestControlOfPlayer(player: GrandTheftMultiplayer.Client.Models.LocalHandle): void;
		stopControlOfPlayer(player: GrandTheftMultiplayer.Client.Models.LocalHandle): void;
		setPlayerWeaponTint(weapon: number, tint: number): void;
		getPlayerWeaponTint(weapon: number): number;
		givePlayerWeaponComponent(weapon: number, component: number): void;
		removePlayerWeaponComponent(weapon: number, component: number): void;
		hasPlayerWeaponComponent(weapon: number, component: number): boolean;
		getAllWeaponComponents(weapon: GrandTheftMultiplayer.Shared.WeaponHash): System.Array<any>;
		getPlayerCurrentWeapon(): number;
		getWeaponName(weapon: number): string;
		removeAllPlayerWeapons(): void;
		doesPlayerHaveWeapon(weapon: number): boolean;
		removePlayerWeapon(weapon: number): void;
		createRaycast(start: GrandTheftMultiplayer.Shared.Math.Vector3, end: GrandTheftMultiplayer.Shared.Math.Vector3, flag: number, ignoreEntity: any): GrandTheftMultiplayer.Client.Javascript.ScriptContext.Raycast;
		showCursor(show: boolean): void;
		isCursorShown(): boolean;
		getCursorPosition(): System.Drawing.PointF;
		getCursorPositionMantainRatio(): System.Drawing.PointF;
		getCursorPositionMaintainRatio(): System.Drawing.PointF;
		showLoadingPrompt(loadingText: string, busySpinnerType: number): void;
		hideLoadingPrompt(): void;
		isLoadingPromptActive(): boolean;
		isHudComponentActive(componentId: number): boolean;
		showHudComponentThisFrame(componentId: number): void;
		hideHudComponentThisFrame(componentId: number): void;
		fadeScreenOut(time: number): void;
		fadeScreenIn(time: number): void;
		isMainMenuOpen(): boolean;
		isScreenFadedIn(): boolean;
		setRadarZoom(zoom: number): void;
		isScreenFadedOut(): boolean;
		isScreenFadingIn(): boolean;
		isScreenFadingOut(): boolean;
		worldToScreen(pos: GrandTheftMultiplayer.Shared.Math.Vector3): System.Drawing.PointF;
		worldToScreenMantainRatio(pos: GrandTheftMultiplayer.Shared.Math.Vector3): System.Drawing.PointF;
		worldToScreenMaintainRatio(pos: GrandTheftMultiplayer.Shared.Math.Vector3): System.Drawing.PointF;
		screenToWorld(pos: System.Drawing.PointF): GrandTheftMultiplayer.Shared.Math.Vector3;
		screenToWorldMantainRatio(pos: System.Drawing.PointF): GrandTheftMultiplayer.Shared.Math.Vector3;
		screenToWorldMaintainRatio(pos: System.Drawing.PointF): GrandTheftMultiplayer.Shared.Math.Vector3;
		screenToWorld(pos: System.Drawing.PointF, camPos: GrandTheftMultiplayer.Shared.Math.Vector3, camRot: GrandTheftMultiplayer.Shared.Math.Vector3): GrandTheftMultiplayer.Shared.Math.Vector3;
		screenToWorldMantainRatio(pos: System.Drawing.PointF, camPos: GrandTheftMultiplayer.Shared.Math.Vector3, camrot: GrandTheftMultiplayer.Shared.Math.Vector3): GrandTheftMultiplayer.Shared.Math.Vector3;
		screenToWorldMaintainRatio(pos: System.Drawing.PointF, camPos: GrandTheftMultiplayer.Shared.Math.Vector3, camrot: GrandTheftMultiplayer.Shared.Math.Vector3): GrandTheftMultiplayer.Shared.Math.Vector3;
		showMissionPassedMessage(message: string, time?: number): void;
		showColoredShard(message: string, description: string, textColor: number, bgColor: number, time?: number): void;
		showOldMessage(message: string, time?: number): void;
		showRankupMessage(message: string, subtitle: string, rank: number, time?: number): void;
		showWeaponPurchasedMessage(bigMessage: string, weaponName: string, weapon: number, time?: number): void;
		showMpMessageLarge(message: string, time?: number): void;
		showCustomShard(funcName: string, ...parameters: any[]): void;
		setSetting(name: string, value: any): void;
		getSetting(name: string): any;
		doesSettingExist(name: string): boolean;
		removeSetting(name: string): void;
		loadConfig(config: string): GrandTheftMultiplayer.Client.Javascript.XmlGroup;
		fromJson(json: string): any;
		toJson(data: any): string;
		getStreamedPlayers(): System.Array<any>;
		getStreamedVehicles(): System.Array<any>;
		getStreamedObjects(): System.Array<any>;
		getStreamedPickups(): System.Array<any>;
		getStreamedPeds(): System.Array<any>;
		getStreamedMarkers(): System.Array<any>;
		getStreamedTextLabels(): System.Array<any>;
		getAllPlayers(): System.Array<any>;
		getAllVehicles(): System.Array<any>;
		getAllObjects(): System.Array<any>;
		getAllPickups(): System.Array<any>;
		getAllPeds(): System.Array<any>;
		getAllMarkers(): System.Array<any>;
		getAllTextLabels(): System.Array<any>;
		playPoliceReport(reportName: string): void;
		setWeather(weather: number): void;
		getWeather(): number;
		resetWeather(): void;
		setNextWeather(weather: number): void;
		getNextWeather(): number;
		setWeatherTransitionType(weatherTransitionType: number): void;
		getWeatherTransitionType(): number;
		transitionToWeather(weather: number, duration: number): void;
		setTime(hours: number, minutes: number): void;
		getTime(): System.TimeSpan;
		resetTime(): void;
		setSnowEnabled(toggle: boolean, deepPedTracks: boolean, deepVehicleTracks: boolean, infoSubtitle?: boolean): void;
		getOffsetInWorldCoords(entity: GrandTheftMultiplayer.Client.Models.LocalHandle, offset: GrandTheftMultiplayer.Shared.Math.Vector3): GrandTheftMultiplayer.Shared.Math.Vector3;
		getSafeCoordForPed(position: GrandTheftMultiplayer.Shared.Math.Vector3, sidewalk?: boolean, flags?: number): GrandTheftMultiplayer.Shared.Math.Vector3;
		getNextPositionOnStreet(position: GrandTheftMultiplayer.Shared.Math.Vector3, unoccupied?: boolean): GrandTheftMultiplayer.Shared.Math.Vector3;
		getNextPositionOnSidewalk(position: GrandTheftMultiplayer.Shared.Math.Vector3): GrandTheftMultiplayer.Shared.Math.Vector3;
		getOffsetFromWorldCoords(entity: GrandTheftMultiplayer.Client.Models.LocalHandle, pos: GrandTheftMultiplayer.Shared.Math.Vector3): GrandTheftMultiplayer.Shared.Math.Vector3;
		getStreetName(position: GrandTheftMultiplayer.Shared.Math.Vector3): string;
		getZoneName(position: GrandTheftMultiplayer.Shared.Math.Vector3): string;
		getZoneNameLabel(position: GrandTheftMultiplayer.Shared.Math.Vector3): string;
		getGroundHeight(position: GrandTheftMultiplayer.Shared.Math.Vector3): number;
		createProjectile(weapon: number, start: GrandTheftMultiplayer.Shared.Math.Vector3, target: GrandTheftMultiplayer.Shared.Math.Vector3, damage: number, speed?: number, dimension?: number): void;
		createOwnedProjectile(owner: GrandTheftMultiplayer.Client.Models.LocalHandle, weapon: number, start: GrandTheftMultiplayer.Shared.Math.Vector3, target: GrandTheftMultiplayer.Shared.Math.Vector3, damage: number, speed?: number, dimension?: number): void;
		loadInterior(pos: GrandTheftMultiplayer.Shared.Math.Vector3): void;
		setInteriorPropColor(interiorId: number, prop: string, colorId: number): void;
		getInteriorAtPos(pos: GrandTheftMultiplayer.Shared.Math.Vector3): number;
		enableInteriorProp(interiorId: number, propName: string): void;
		disableInteriorProp(interiorId: number, propName: string): void;
		requestIpl(iplName: string): void;
		removeIpl(iplName: string): void;
		isInteriorPropEnabled(interiorId: number, propName: string): boolean;
		setCityBlackout(blackout: boolean): void;
		getCityBlackout(): boolean;
		expandWorldLimits(x: number, y: number, z: number): void;
		getWorldLimits(): GrandTheftMultiplayer.Shared.Math.Vector3;
		setGravityLevel(gravityLevel: number): void;
		getGravityLevel(): number;
		setCloudHatTransition(type: string, transitionTime: number): void;
		clearCloudHat(): void;
		setCloudHatOpacity(opacity: number): void;
		getCloudHatOpacity(): number;
		isAlarmPlaying(alarmName: string): boolean;
		stopAllAlarms(): void;
		startAlarm(alarmName: string): void;
		stopAlarm(alarmName: string): void;
		setGpsActive(active: boolean): void;
		toggleAIPedsSpawning(active: boolean): void;
		isAIPedsSpawningActive(): boolean;
		isFirstPersonCamDisabled(): boolean;
		isVehicleFirstPersonCamDisabled(): boolean;
		toggleVehicleFirstPersonCam(enabled: boolean): void;
		toggleFirstPersonCam(enabled: boolean): void;
		startCoroutine(target: any): void;
		after(time: number, functionname: string, ..._arguments: any[]): number;
		every(time: number, functionname: string, ..._arguments: any[]): number;
		stop(id: number): boolean;
		getCurrentResourceName(): string;
		formatTime(ms: number, format: string): string;
		f(value: number): GrandTheftMultiplayer.Client.Javascript.ScriptContext.fArg;
		sleep(ms: number): void;
		triggerServerEvent(eventName: string, ..._arguments: any[]): void;
		toString(obj: any): string;
		loadAnimationDict(dict: string): void;
	}

	class SoundEvent {
		play(): void;
		stop(): void;
		isPlaying(): boolean;
	}

	class xmlElement {
		constructor();
		getElementData(elementName: string, returnType: number): any;
		hasElementData(elementName: string): boolean;
	}

	class XmlGroup {
		constructor();
		getElementByType(typeName: string): GrandTheftMultiplayer.Client.Javascript.xmlElement;
		getElementsByType(typeName: string): System.Collections.Generic.IEnumerable<GrandTheftMultiplayer.Client.Javascript.xmlElement>;
		getNumberOfElementsOfType(typeName: string): number;
		getSubgroup(groupName: string): GrandTheftMultiplayer.Client.Javascript.XmlGroup;
		hasAnyElementOfType(typeName: string): boolean;
	}

}
